# Copyright Contributors to the Open Cluster Management project

name: Deploy ACM-AAP-AAS-Ops Dev

on: 
  pull_request_target:
    types: [ labeled ]
    branches:
      - main

  # manual trigger
  workflow_dispatch:

jobs:
  function-test:
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1' # The Go version to download (if necessary) and use.
      - name: Removing 'ok-to-test' label
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: ok-to-test
          type: remove
      - name: Checkout cluster and deploy ACM-AAP-AAS-Ops Dev
        run: |
          echo "=== Deploying ACM-AAP-AAS-Operations ==="

          echo "= Checking out cluster ="
          bash ./scripts/ci-deploy.sh aws
        env:
          COLLECTIVE_TOKEN: ${{ secrets.COLLECTIVE_TOKEN }}
